import { Metadata } from "next";
import { Home, Navigation } from "../../components";

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function Page() {
  return (
    <div className="flex justify-center items-center w-full h-full bg-amber-300">
      <Navigation />
      <Home />
    </div>
  );
};