import { Metadata } from "next";
import { Login } from "../../components";

export const metadata: Metadata = {
  title: 'Login',
  description: 'Generated by create next app',
}

export default function Page() {
  return (
    <div className="flex justify-center items-center w-full h-full">
      <Login />
    </div>
  );
};